### ISSUE TITLE
Use Last instead of SingletonFrom in Hospitalization functions

### ISSUE THREAD

**Issue by brynrhodes** [esacinc/CQL-Formatting-and-Usage-Wiki#2]
Based on implementer feedback in [CQLIT-117](https://oncprojectracking.healthit.gov/support/browse/CQLIT-117), the assumption that there would only ever be one immediately preceding emergency room visit within an hour of an inpatient encounter for a given patient does not hold. Guidance from the resolution is that the most recent preceding emergency room visit should be used. The hospitalization functions should be updated to reflect this change.

**Comment by challmpr** [comment]
thank you for presenting this issue. noted by Mathematica

**Comment by brynrhodes** [comment]
Updated as part of the 3.0.0 library
