### ISSUE TITLE
Remove Code System Versions

### ISSUE THREAD

**Issue by brynrhodes** [esacinc/CQL-Formatting-and-Usage-Wiki#3]
Since different terminology systems are managed by different organizations and have different update cycles, measure content typically avoids referencing specific versions of terminologies (value sets and code systems) until there is a publication date, at which time terminology version information is typically provided through a different mechanism (the Binding Parameters Specification for example).

However, the 2.0.0 version of the common library references code system versions specifically. These versions should be removed.

**Comment by jsaddmpr** [comment]
thank you for presenting this issue. noted by Mathematica

**Comment by brynrhodes** [comment]
Removed as part of the 3.0.0 library.
