### ISSUE TITLE
Add Observation Status Functions

### ISSUE THREAD

**Issue by brynrhodes** [esacinc/CQL-Formatting-and-Usage-Wiki#4]
The current Hospitalization functions provide a way to define criteria with respect to an "episode-of-care" whether that is a single in-patient encounter, or an in-patient encounter with an immediately preceding emergency department visit. However, there are scenarios that need to be able to account for episodes of care that may include observation time, as well as potential emergency department visits. To account for this, new hospitalization functions that account for observation status should be added, as described here:

https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Cooking%20With%20CQL/27/67_ObservationStatus.cql#L188

**Comment by jsaddmpr** [comment]
thank you for presenting this issue. noted by Mathematica

**Comment by brynrhodes** [comment]
Added Observation and Outpatient functions, but should we also add equivalents for the other functions that are based on hospitalization? (like Hospital Arrival Time, and Departure Time, etc.)

**Comment by brynrhodes** [comment]
Also, for Observation Services, I used the OID suggested during the Cooking with CQL session, but that obviously needs review, and we need to establish one for Outpatient Services as well.

**Comment by brynrhodes** [comment]
Functions added as part of the update to the 3.0 library.
