### ISSUE TITLE
May 2019 STU not Normative Ballot for CQL

### ISSUE THREAD

**Issue by p9g** [esacinc/CQL-Formatting-and-Usage-Wiki#8]
https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/wiki/eCQM-Known-Issues#cql-clarifications-and-enhancements says that May 2019 will be a Normative ballot for CQL.  Latest thinking is that May 2019 will be a STU ballot, and a Normative ballot would follow in a future ballot cycle.

**Comment by brynrhodes** [comment]
Thanks @p9g , I updated the language there to reference the May 2019 STU ballot.
